(() => {
'use strict';

const STORAGE='checkout-lab-session-v1';
const LEGACY_STORAGE='checkout-lab-game-v2';
const SETTINGS='checkout-lab-settings-v3';
const COLORS=['#e83f5b','#43d08a','#f7b844','#6aa7ff','#bd75ff','#ff7d4d'];
const BOGEY=new Set([169,168,166,165,163,162,159]);
const preferredDoubles=['D20','D16','D18','D12','D10','D8','D14','D6','D4','D2','D1','BULL'];
const canonical={
170:['T20','T20','BULL'],167:['T20','T19','BULL'],164:['T20','T18','BULL'],161:['T20','T17','BULL'],160:['T20','T20','D20'],158:['T20','T20','D19'],156:['T20','T20','D18'],154:['T20','T18','D20'],152:['T20','T20','D16'],150:['T20','T18','D18'],148:['T20','T16','D20'],146:['T20','T18','D16'],144:['T20','T20','D12'],142:['T20','T14','D20'],140:['T20','T20','D10'],138:['T20','T18','D12'],136:['T20','T20','D8'],134:['T20','T14','D16'],132:['BULL','BULL','D16'],130:['T20','T20','D5'],128:['T18','T18','D10'],126:['T19','T19','D6'],124:['T20','T16','D8'],121:['T20','T11','D14'],120:['T20','S20','D20'],118:['T20','S18','D20'],116:['T20','S16','D20'],114:['T20','S14','D20'],112:['T20','S12','D20'],110:['T20','S10','D20'],108:['T20','S16','D16'],106:['T20','S14','D16'],104:['T18','S18','D16'],102:['T20','S10','D16'],100:['T20','D20'],98:['T20','D19'],96:['T20','D18'],94:['T18','D20'],92:['T20','D16'],90:['T18','D18'],88:['T16','D20'],86:['T18','D16'],84:['T20','D12'],82:['T14','D20'],80:['T20','D10'],78:['T18','D12'],76:['T20','D8'],74:['T14','D16'],72:['T16','D12'],70:['T18','D8'],68:['T20','D4'],66:['T10','D18'],64:['T16','D8'],62:['T10','D16'],61:['T15','D8'],
60:['S20','D20'],59:['S19','D20'],58:['S18','D20'],57:['S17','D20'],56:['S16','D20'],
55:['S15','D20'],54:['S14','D20'],53:['S13','D20'],52:['S12','D20'],51:['S11','D20'],
50:['BULL'],49:['S9','D20'],48:['S16','D16'],47:['S15','D16'],46:['S14','D16'],
45:['S13','D16'],44:['S12','D16'],43:['S11','D16'],42:['S10','D16'],41:['S9','D16']
};

const hit=(label,value,multiplier,number)=>({label,value,multiplier,number,isDouble:multiplier===2,isTreble:multiplier===3});
const MISS={label:'MISS',value:0,multiplier:0,number:0,isDouble:false,isTreble:false};
const ALL=[MISS];
for(let n=1;n<=20;n++){ALL.push(hit(`S${n}`,n,1,n),hit(`D${n}`,n*2,2,n),hit(`T${n}`,n*3,3,n));}
ALL.push(hit('25',25,1,25),hit('BULL',50,2,25));
const byLabel=Object.fromEntries(ALL.map(h=>[h.label,h]));
const finishers=ALL.filter(h=>h.isDouble);
const playable=ALL.filter(h=>h.label!=='MISS');
const POSSIBLE_VISIT_TOTALS=(()=>{const set=new Set();for(const a of ALL)for(const b of ALL)for(const c of ALL)set.add(a.value+b.value+c.value);return set;})();
let wakeLockSentinel=null;
let audioContext=null;
function isPossibleVisitTotal(v){return Number.isInteger(v)&&v>=0&&v<=180&&POSSIBLE_VISIT_TOTALS.has(v);}
function prefixReachable(total,maxDarts=2){if(total===0)return true;if(total<0)return false;for(const a of ALL){if(a.value===total)return true;if(maxDarts>=2)for(const b of ALL)if(a.value+b.value===total)return true;}return false;}
function validFinishDoubles(total){const preferred=(canonical[total]||[]).at(-1);return finishers.filter(f=>prefixReachable(total-f.value,2)).sort((a,b)=>{if(a.label===preferred)return -1;if(b.label===preferred)return 1;const ai=preferredDoubles.indexOf(a.label),bi=preferredDoubles.indexOf(b.label);return (ai<0?99:ai)-(bi<0?99:bi);});}
function validCheckoutDartCounts(total,doubleLabel){const d=byLabel[doubleLabel];if(!d?.isDouble)return[];const rest=total-d.value,out=[];if(rest===0)out.push(1);if(rest>=0&&ALL.some(a=>a.value===rest))out.push(2);if(rest>=0&&ALL.some(a=>ALL.some(b=>a.value+b.value===rest)))out.push(3);return [...new Set(out)];}
function playSound(kind='score'){
 if(!state.sound)return;
 try{audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();const now=audioContext.currentTime;const tones=kind==='180'?[[880,.08],[1175,.09],[1568,.14]]:kind==='leg'?[[660,.09],[880,.1],[1320,.18]]:kind==='bust'?[[180,.13],[145,.18]]:[[520,.055]];let t=now;for(const [freq,dur] of tones){const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.055,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+dur+.02);t+=dur*.72;}}catch{}
}
function haptic(kind='score'){if(!state.vibration||!navigator.vibrate)return;try{navigator.vibrate(kind==='180'?[35,30,35,30,70]:kind==='leg'?[50,35,90]:kind==='bust'?[90]:[25]);}catch{}}
async function syncWakeLock(){
 const should=state.wakeLock&&state.screen==='game'&&!!state.game&&!state.game.winner&&document.visibilityState==='visible';
 if(!should){if(wakeLockSentinel){try{await wakeLockSentinel.release();}catch{}wakeLockSentinel=null;}return;}
 if(wakeLockSentinel||!('wakeLock' in navigator))return;
 try{wakeLockSentinel=await navigator.wakeLock.request('screen');wakeLockSentinel.addEventListener('release',()=>{wakeLockSentinel=null;});}catch{wakeLockSentinel=null;}
}
function toggleFocusMode(){state.focusMode=!state.focusMode;document.body.classList.toggle('focus-mode',state.focusMode);if(state.focusMode){document.documentElement.requestFullscreen?.().catch(()=>{});}else if(document.fullscreenElement){document.exitFullscreen?.().catch(()=>{});}save();render();}


function hitRank(h,pos,total){
 if(pos===total-1){const i=preferredDoubles.indexOf(h.label);return i<0?40:i;}
 if(h.isTreble)return Math.max(0,20-h.number);
 if(h.label==='BULL')return 34;
 if(h.multiplier===1)return 45+Math.max(0,20-h.number);
 return 80;
}
function routeRank(route){return route.length*100+route.reduce((s,h,i)=>s+hitRank(h,i,route.length),0)-route.slice(0,-1).filter(h=>h.isTreble).length*12;}\nfunction normalizeCheckoutRoute(route){\n const out=[...route],setupEnd=Math.max(0,out.length-1);\n const trebles=out.slice(0,setupEnd).filter(h=>h.isTreble).sort((a,b)=>b.number-a.number);\n let ti=0;for(let i=0;i<setupEnd;i++)if(out[i].isTreble)out[i]=trebles[ti++];\n return out;\n}
const routeCache=new Map();
function checkoutRoutes(score,darts=3,limit=4){
 const key=`${score}-${darts}-${limit}`; if(routeCache.has(key)) return routeCache.get(key);
 if(score<2||score>170||darts<1)return [];
 const routes=[];
 for(const f of finishers)if(f.value===score)routes.push([f]);
 if(darts>=2)for(const a of playable)for(const f of finishers)if(a.value+f.value===score)routes.push([a,f]);
 if(darts>=3)for(const a of playable)for(const b of playable){const left=score-a.value-b.value;for(const f of finishers)if(f.value===left)routes.push([a,b,f]);}
 const normalized=routes.map(normalizeCheckoutRoute);\n const unique=[...new Map(normalized.map(r=>[r.map(h=>h.label).join('-'),r])).values()];
 const pref=normalizeCheckoutRoute((canonical[score]||[]).map(label=>byLabel[label]).filter(Boolean)).map(h=>h.label).join('-');
 unique.sort((a,b)=>{const ak=a.map(h=>h.label).join('-'),bk=b.map(h=>h.label).join('-');if(ak===pref)return -1;if(bk===pref)return 1;return routeRank(a)-routeRank(b);});
 const out=unique.slice(0,limit);routeCache.set(key,out);return out;
}
function preparation(score){
 const candidates=ALL.filter(h=>h.isTreble||h.label==='BULL').map(h=>({hit:h,remainder:score-h.value})).filter(c=>c.remainder>1&&!BOGEY.has(c.remainder)).map(c=>({...c,routes:checkoutRoutes(c.remainder,3,1)})).filter(c=>c.routes.length);
 candidates.sort((a,b)=>a.routes[0].length-b.routes[0].length||routeRank(a.routes[0])-routeRank(b.routes[0]));return candidates[0]||null;
}

const state={
 screen:'setup', theme:'dark', mode:501, customScore:701, names:['Даня','Соперник'], legs:3,
 game:null, undo:[], redo:[], inputMode:'visit', multiplier:1, visitValue:'', mobileMenu:false, settingsOpen:false, checkoutConfirm:null, search:'', historyOpen:false, moment:null, previewPlayerId:null,
 sound:false, vibration:false, wakeLock:true, focusMode:false, inputError:'', lastSubmitAt:0, editLastOpen:false, editLastValue:'', editLastDouble:'', editLastDarts:3
};

function clone(x){return JSON.parse(JSON.stringify(x));}
function id(){return (crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`);}
function newPlayer(name,index,score){return{id:id(),name,score,color:COLORS[index%COLORS.length],darts:0,total:0,visits:0,high:0,wins:0};}
function save(){
 try{localStorage.setItem(STORAGE,JSON.stringify({game:state.game,undo:state.undo,redo:state.redo}));}catch{}
 try{localStorage.setItem(SETTINGS,JSON.stringify({theme:state.theme,names:state.names,legs:state.legs,mode:state.mode,customScore:state.customScore,sound:state.sound,vibration:state.vibration,wakeLock:state.wakeLock,focusMode:state.focusMode}));}catch{}
}
function load(){
 try{const session=JSON.parse(localStorage.getItem(STORAGE)||'null');if(session?.game?.players){state.game=session.game;state.undo=Array.isArray(session.undo)?session.undo:[];state.redo=Array.isArray(session.redo)?session.redo:[];}else{const legacy=JSON.parse(localStorage.getItem(LEGACY_STORAGE)||'null');if(legacy?.players)state.game=legacy;}}catch{}
 try{const settings=JSON.parse(localStorage.getItem(SETTINGS)||'null');if(settings)Object.assign(state,settings);}catch{}
}
function snapshot(){if(!state.game)return;state.undo.push(clone(state.game));if(state.undo.length>40)state.undo.shift();state.redo=[];}
function activePlayer(){return state.game?.players[state.game.active]||null;}
function previewPlayer(){return state.previewPlayerId?state.game?.players.find(p=>p.id===state.previewPlayerId)||null:null;}
function displayPlayer(){return previewPlayer()||activePlayer();}
function currentTotal(){return (state.game?.current||[]).reduce((s,h)=>s+h.value,0);}
function remaining(){const p=activePlayer();return p?p.score-currentTotal():0;}
function avg(p){return p.darts?(p.total/p.darts*3).toFixed(1):'—';}

function startGame(){
 const score=state.mode===0?Math.max(2,Number(state.customScore)||501):state.mode;
 const players=state.names.map(n=>n.trim()).filter(Boolean).map((n,i)=>newPlayer(n,i,score));if(!players.length)return;
 state.game={startScore:score,players,active:0,current:[],history:[],legsToWin:Number(state.legs)||1,winner:null};state.undo=[];state.redo=[];state.visitValue='';state.inputError='';state.previewPlayerId=null;state.screen='game';save();render();
}
function applyRecordedVisit(game,visit){
 const idx=game.players.findIndex(x=>x.id===visit.playerId);if(idx<0)return game;game.active=idx;const p=game.players[idx],start=p.score,total=Number(visit.total)||0,bust=!!visit.bust,checkout=!!visit.checkout,dartCount=Number(visit.dartCount)||3;
 p.darts+=dartCount;p.total+=bust?0:total;p.visits++;p.high=Math.max(p.high,bust?0:total);
 if(checkout){p.wins++;if(p.wins>=game.legsToWin)game.winner=p.id;else game.players=game.players.map(x=>({...x,score:game.startScore}));}
 else if(!bust)p.score=start-total;
 game.history.push({...clone(visit),start,dartCount});game.active=(idx+1)%game.players.length;game.current=[];return game;
}
function rebuildGame(history){
 const g=state.game;if(!g)return null;const base={startScore:g.startScore,players:g.players.map(p=>({id:p.id,name:p.name,color:p.color,score:g.startScore,darts:0,total:0,visits:0,high:0,wins:0})),active:0,current:[],history:[],legsToWin:g.legsToWin,winner:null};
 for(const v of history)applyRecordedVisit(base,v);return base;
}
function finishVisit(hits,forcedBust=false,dartCount=hits.length){
 const g=state.game,p=activePlayer();if(!g||!p||!hits.length)return;
 snapshot();const total=hits.reduce((sum,h)=>sum+h.value,0),left=p.score-total,last=hits[hits.length-1];
 const checkout=left===0&&last.isDouble&&!forcedBust,bust=forcedBust||left<0||left===1||(left===0&&!last.isDouble);
 const next=clone(g);applyRecordedVisit(next,{playerId:p.id,start:p.score,hits,total,bust,checkout,dartCount});state.game=next;state.visitValue='';state.inputError='';state.previewPlayerId=null;
 const kind=bust?'bust':checkout?'leg':total===180?'180':'score';state.moment=bust?{label:'BUST',tone:'bust',at:Date.now()}:checkout?{label:next.winner?'МАТЧ!':'LEG!',tone:'leg',at:Date.now()}:total===180?{label:'180!',tone:'max',at:Date.now()}:null;
 playSound(kind);haptic(kind);save();render();
 if(state.moment){const stamp=state.moment.at;setTimeout(()=>{if(state.moment?.at===stamp){state.moment=null;render();}},900);}
}
function addDart(h){
 const g=state.game,p=activePlayer();if(!g||!p||g.winner)return;const hits=[...g.current,h],left=p.score-hits.reduce((sum,x)=>sum+x.value,0),bad=left===0&&!h.isDouble;
 if(left<0||left===1||bad)return finishVisit(hits,true);if(left===0||hits.length===3)return finishVisit(hits);
 snapshot();g.current=hits;save();render();
}
function requestVisitSubmit(){
 const now=Date.now();if(now-state.lastSubmitAt<300)return;const value=Number(state.visitValue),g=state.game,p=activePlayer();if(!g||!p||state.visitValue===''||!Number.isInteger(value)||value<0||value>180)return;
 if(!isPossibleVisitTotal(value)){state.inputError=`${value} нельзя набрать за 3 дротика`;render();return;}
 state.inputError='';state.lastSubmitAt=now;
 if(p.score-value===0){const doubles=validFinishDoubles(value);if(!doubles.length){state.inputError='Нет корректного Double Out для этой суммы';render();return;}const selected=doubles[0].label,counts=validCheckoutDartCounts(value,selected);state.checkoutConfirm={value,doubles:doubles.map(d=>d.label),selected,darts:counts[0]||3};render();return;}
 finishVisit([{label:`Σ${value}`,value,multiplier:1,number:value,isDouble:false,isTreble:false}],false,3);
}
function confirmCheckout(label){
 const data=state.checkoutConfirm;if(!data)return;const value=data.value;state.checkoutConfirm=null;const d=byLabel[label];if(!d?.isDouble)return;const h={label:`Σ${value} · ${label}`,value,multiplier:2,number:value,isDouble:true,isTreble:false,finishLabel:label};finishVisit([h],false,Number(data.darts)||3);
}
function cancelCheckout(){state.checkoutConfirm=null;state.lastSubmitAt=0;render();}
function undo(){if(!state.undo.length||!state.game)return;state.redo.push(clone(state.game));state.game=state.undo.pop();state.visitValue='';state.inputError='';state.previewPlayerId=null;save();render();}
function redo(){if(!state.redo.length||!state.game)return;state.undo.push(clone(state.game));state.game=state.redo.pop();state.visitValue='';state.inputError='';state.previewPlayerId=null;save();render();}
function nav(screen){state.screen=screen;state.mobileMenu=false;state.settingsOpen=false;save();render();}
function openEditLast(){const v=state.game?.history?.at(-1);if(!v)return;state.editLastOpen=true;state.editLastValue=String(v.total);state.editLastDarts=Number(v.dartCount)||3;state.editLastDouble=v.checkout?(v.hits?.at(-1)?.finishLabel||String(v.hits?.at(-1)?.label||'').match(/D\d+|BULL/)?.[0]||''):'';render();}
function deleteLastVisit(){if(!state.game?.history.length)return;snapshot();state.game=rebuildGame(state.game.history.slice(0,-1));state.editLastOpen=false;state.visitValue='';state.inputError='';save();render();}
function applyEditedLastVisit(){
 if(!state.game?.history.length)return;const value=Number(state.editLastValue);if(!isPossibleVisitTotal(value)){state.inputError=`${value} нельзя набрать за 3 дротика`;render();return;}
 const history=state.game.history.slice(0,-1),base=rebuildGame(history);if(!base)return;const p=base.players[base.active],left=p.score-value;let finish='';if(left===0){const valid=validFinishDoubles(value).map(d=>d.label);if(!valid.length)return;if(!valid.includes(state.editLastDouble))state.editLastDouble=valid[0];finish=state.editLastDouble;}
 snapshot();const checkout=left===0&&!!finish,bust=left<0||left===1||(left===0&&!finish),h={label:`Σ${value}${finish?` · ${finish}`:''}`,value,multiplier:finish?2:1,number:value,isDouble:!!finish,isTreble:false,finishLabel:finish||undefined};applyRecordedVisit(base,{playerId:p.id,start:p.score,hits:[h],total:value,bust,checkout,dartCount:checkout?Number(state.editLastDarts)||3:3});state.game=base;state.editLastOpen=false;state.visitValue='';state.inputError='';save();render();
}
function keypad(k){
 state.inputError='';if(k==='back')state.visitValue=state.visitValue.slice(0,-1);else if(k==='ok')return requestVisitSubmit();else if(/^\d$/.test(k)){const next=(state.visitValue+k).replace(/^0+(?=\d)/,'');if(Number(next)<=180&&next.length<=3)state.visitValue=next;}
 render();
}
function quick(v){state.visitValue=String(v);state.inputError='';render();}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

const I={target:'◎',plus:'＋',game:'◉',book:'▤',stats:'▥',sun:'☀',moon:'☾',undo:'↶',redo:'↷',menu:'☰',close:'×',back:'⌫'};
function header(){return `<header class="topbar"><button class="brand" data-nav="setup"><span class="brand-mark">◎</span><span>CHECKOUT<span>LAB</span></span></button><nav>
<button class="nav-item ${state.screen==='setup'?'active':''}" data-nav="setup">${I.plus}<span>Новая игра</span></button>${state.game?`<button class="nav-item ${state.screen==='game'?'active':''}" data-nav="game">${I.game}<span>Матч</span></button>`:''}<button class="nav-item ${state.screen==='checkouts'?'active':''}" data-nav="checkouts">${I.book}<span>Закрытия</span></button><button class="nav-item" data-table-link>${I.book}<span>Таблица 2–170</span></button><button class="nav-item ${state.screen==='stats'?'active':''}" data-nav="stats">${I.stats}<span>Статистика</span></button></nav><button class="icon-button settings-toggle" aria-label="Настройки" title="Настройки">⚙</button><button class="icon-button theme-toggle" aria-label="Сменить тему">${state.theme==='dark'?I.sun:I.moon}</button><button class="mobile-menu-button" aria-label="Меню">${state.mobileMenu?I.close:I.menu}</button></header>`;}
function mobileMenu(){if(!state.mobileMenu)return'';return `<div class="mobile-menu"><button data-nav="setup">＋ Новая игра</button>${state.game?'<button data-nav="game">◉ Матч</button>':''}<button data-nav="checkouts">▤ Закрытия</button><button data-table-link>▤ Таблица закрытий 2–170</button><button data-nav="stats">▥ Статистика</button>${state.game?'<button class="focus-toggle">⛶ Режим у мишени</button>':''}<button class="sound-toggle">${state.sound?'🔊':'🔇'} Звук: ${state.sound?'вкл':'выкл'}</button><button class="vibration-toggle">${state.vibration?'◉':'○'} Вибрация: ${state.vibration?'вкл':'выкл'}</button><button class="wake-toggle">${state.wakeLock?'☀':'☾'} Экран не гаснет: ${state.wakeLock?'да':'нет'}</button><button class="theme-toggle">${state.theme==='dark'?'☀ Светлая тема':'☾ Тёмная тема'}</button></div>`;}

function setupView(){
 return `<section class="setup-page"><div class="setup-intro"><span class="kicker">ДАРТС БЕЗ ЛИШНЕГО</span><h1>Бросай.<br><i>Мы посчитаем.</i></h1><p>Счётчик для дартса 301/501: точные закрытия, Double Out, до 8 игроков. Работает онлайн и офлайн.</p>${state.game?'<button class="continue" data-nav="game">◉ Продолжить текущий матч</button>':''}</div><div class="setup-card panel"><div class="step"><span>01</span><div><h2>Выбери игру</h2><p>Double Out включён</p></div></div><div class="mode-grid">${[301,501,0].map(v=>`<button data-mode="${v}" class="${state.mode===v?'active':''}"><strong>${v||'СВОЯ'}</strong><small>${v?'очков':'режим'}</small></button>`).join('')}</div>${state.mode===0?`<label class="field-label">Начальный счёт<input id="custom-score" type="number" min="2" max="5001" value="${state.customScore}"></label>`:''}<div class="step"><span>02</span><div><h2>Добавь игроков</h2><p>От одного до восьми</p></div></div><div class="name-list">${state.names.map((n,i)=>`<div class="name-row"><span style="background:${COLORS[i%COLORS.length]}">${i+1}</span><input class="player-name" data-index="${i}" value="${esc(n)}" placeholder="Игрок ${i+1}">${state.names.length>1?`<button class="remove-player" data-index="${i}">×</button>`:'<span></span>'}</div>`).join('')}</div>${state.names.length<8?'<button class="add-player">＋ Добавить игрока</button>':''}<div class="settings-row"><label>Легов для победы<select id="legs-select">${[1,2,3,4,5,6,7].map(n=>`<option ${state.legs===n?'selected':''}>${n}</option>`).join('')}</select></label><span>⚙ Double Out · Bull разрешён</span></div><button class="start-button">НАЧАТЬ МАТЧ <span>◉</span></button></div></section>`;
}
function playerCards(mobile=false){const g=state.game;if(!g)return'';return g.players.map((p,i)=>{const active=i===g.active,preview=state.previewPlayerId===p.id&&!active;return `<div class="${mobile?'m-player':'player'} ${active?'active':''} ${preview?'previewing':''}" style="--player:${p.color}" data-preview-player="${p.id}" role="button" tabindex="0" title="${active?'Текущий ход':'Показать выход на закрытие'}"><span class="${mobile?'m-player-line':'player-dot'}"></span><div class="player-copy"><strong>${esc(p.name)}</strong><small>${preview?'ПРОСМОТР · ':active&&mobile?'ХОД · ':''}AVG ${avg(p)}</small></div><b>${p.score}</b><em>${mobile?`L${p.wins}`:p.wins}</em></div>`;}).join('');}
function nextTurnMarkup(compact=false){const g=state.game;if(!g||g.players.length<2)return'';const ordered=[];for(let k=1;k<g.players.length;k++)ordered.push(g.players[(g.active+k)%g.players.length]);if(compact)return `<span class="next-player">СЛЕДУЮЩИЙ <b>${esc(ordered[0].name)}</b></span>`;return `<div class="turn-queue"><span>ОЧЕРЕДЬ</span><strong>${ordered.map(p=>esc(p.name)).join(' → ')}</strong></div>`;}
function routeHtml(route){return route.map(h=>`<b class="route-hit ${h.isTreble?'treble':h.isDouble?'double':h.label==='BULL'?'bull-hit':'single-hit'}">${h.label}</b>`).join('<i>→</i>');}
function visitPreview(){const p=activePlayer();if(!p||state.visitValue==='')return '<span>Введите сумму подхода</span>';const v=Number(state.visitValue);if(!isPossibleVisitTotal(v))return `<span class="preview-impossible">${v} нельзя набрать за 3 дротика</span>`;const left=p.score-v;if(left<0||left===1)return '<span class="preview-bust">BUST — счёт не изменится</span>';if(left===0)return '<span class="preview-checkout">ЗАКРЫТИЕ · выберите последнее удвоение</span>';return `<span>останется <b>${left}</b></span>`;}
function historyRows(limit=7){const g=state.game;if(!g)return'';return g.history.slice(-limit).reverse().map((v,i)=>{const p=g.players.find(x=>x.id===v.playerId),editable=i===0;return `<div class="visit ${editable?'editable-last':''}" ${editable?'data-edit-last="1" title="Изменить последний подход"':''}><span style="color:${p?.color||'#fff'}">${esc(p?.name||'')}</span><span>${v.hits.map(h=>esc(h.label)).join(' · ')}</span><b class="${v.bust?'bust':''}">${v.bust?'BUST':v.total}</b>${editable?'<i class="edit-mark">✎</i>':''}</div>`;}).join('');}
function adviceMarkup(mobile=false,scoreOverride=null,preview=false){const rem=scoreOverride??remaining(),darts=preview?3:Math.max(1,3-(state.game?.current.length||0)),routes=checkoutRoutes(rem,darts,4);if(routes.length){return `<div class="${mobile?'m-advice checkout':'checkout-advice checkout-live'} ${preview?'preview-advice':''}"><div><span class="eyebrow">${preview?'ВЫХОД ИГРОКА':'ВЫХОД НА ЗАКРЫТИЕ'}</span><strong class="route-main">${routeHtml(routes[0])}</strong></div>${routes.slice(1).map(r=>`<span class="route-alt">${routeHtml(r)}</span>`).join('')}</div>`;}
 if(preview){const prep=preparation(rem);return `<div class="${mobile?'m-advice preview-no-checkout':'checkout-advice preview-no-checkout'}"><div><span class="eyebrow">ЗАКРЫТИЯ НЕТ</span><strong>${prep?`${prep.hit.label} → оставить ${prep.remainder}`:'Набирай максимум'}</strong></div></div>`;}
 if(mobile){const last=state.game?.history.at(-1),lp=last&&state.game.players.find(x=>x.id===last.playerId);return `<div class="m-advice compact-recent"><span>ПОСЛЕДНИЙ</span><strong>${last?`${esc(lp?.name||'')} · ${last.bust?'BUST':last.total}`:'Матч только начался'}</strong><button class="open-history">История ›</button></div>`;}
 const prep=preparation(rem);return `<div class="checkout-advice"><div><span class="eyebrow">ПОДГОТОВКА</span><strong>${prep?`${prep.hit.label} → оставить ${prep.remainder}`:'Набирай максимум'}</strong></div></div>`;
}
function historyDrawer(){if(!state.historyOpen||!state.game)return'';return `<div class="drawer-backdrop close-history"><section class="history-drawer panel" onclick="event.stopPropagation()"><div class="drawer-handle"></div><div class="drawer-head"><div><span>ИСТОРИЯ МАТЧА</span><strong>Последние подходы</strong></div><button class="close-history">×</button></div><div class="drawer-list">${historyRows(18)||'<div class="m-empty-history">Подходов пока нет</div>'}</div></section></div>`;}
function momentOverlay(){return state.moment?`<div class="game-moment ${state.moment.tone}">${state.moment.label}</div>`:'';}
function winnerScoreline(g){const w=g.players.find(p=>p.id===g.winner);if(!w)return'';if(g.players.length===2){const o=g.players.find(p=>p.id!==g.winner);return `${w.wins} : ${o?.wins||0}`;}return g.players.map(p=>`${esc(p.name)} ${p.wins}`).join(' · ');}
function desktopGame(){const g=state.game,p=activePlayer(),view=displayPlayer();if(!g||!p||!view)return'';if(g.winner)return `<section class="game-layout desktop-game"><div class="winner panel"><span>ПОБЕДИТЕЛЬ МАТЧА</span><h1>${esc(g.players.find(x=>x.id===g.winner)?.name||'')}</h1><div class="winner-score">${winnerScoreline(g)}</div><button class="primary play-again">↻ Сыграть ещё</button></div></section>`;
 const preview=!!previewPlayer(),rem=preview?view.score:remaining();return `<section class="game-layout desktop-game desktop-v4 desktop-v5 ${preview?'is-previewing':''}"><aside class="players-panel panel"><div class="panel-title"><span class="section-icon">◉</span><b>ИГРОКИ</b><span>НАЖМИ ДЛЯ ВЫХОДА</span></div><div class="desktop-player-list">${playerCards()}</div>${nextTurnMarkup(false)}</aside><section class="score-stage panel"><div class="stage-topline"><div class="turn-label"><span style="background:${view.color}"></span><div><small>${preview?'ПРОСМОТР ЗАКРЫТИЯ':'СЕЙЧАС БРОСАЕТ'}</small><b>${esc(view.name)}</b></div></div>${preview?`<div class="preview-live-actions"><span class="live-turn-pill">ХОД: <b>${esc(p.name)}</b> · ${p.score}</span><button class="clear-preview stage-back">↩ Вернуться</button></div>`:`<span class="stage-leg">ЛЕГ ${Math.max(...g.players.map(x=>x.wins))+1}</span>`}</div><div class="score-ring ${preview?'preview-ring':''}"><small>${preview?'СЧЁТ ИГРОКА':'ОСТАЛОСЬ'}</small><strong>${Math.max(0,rem)}</strong><span>${preview?'3 ДРОТИКА · ПРОСМОТР':g.current.length?g.current.map(h=>h.label).join(' · '):'3 ДРОТИКА'}</span></div>${adviceMarkup(false,rem,preview)}</section><aside class="input-panel panel desktop-input-v4"><div class="desktop-entry-head"><div><span class="eyebrow">ВВОД ПОДХОДА</span><strong>Введите сумму</strong><small class="entry-subtitle">для ${esc(p.name)} · цифры → Enter</small></div><div class="history-actions"><button class="undo" title="Отменить последний подход" ${!state.undo.length?'disabled':''}>↶</button><button class="redo" title="Вернуть подход" ${!state.redo.length?'disabled':''}>↷</button></div></div>${desktopVisitInput()}<div class="desktop-history"><div class="history-title"><span>◷</span> Последние подходы <small>${g.history.length}</small></div><div class="visit-list">${historyRows(7)||'<div class="empty-mini">Подходов пока нет</div>'}</div></div></aside></section>`;}
function dartPad(){return `<div class="multipliers">${[[1,'S','ОДИНОЧНЫЙ'],[2,'D','УДВОЕНИЕ'],[3,'T','УТРОЕНИЕ']].map(([m,l,s])=>`<button data-mult="${m}" class="${state.multiplier===m?'active ':''}${m===1?'single':m===2?'double':'treble'}">${l}<small>${s}</small></button>`).join('')}</div><div class="number-grid">${Array.from({length:20},(_,i)=>i+1).map(n=>`<button data-dart="${n}">${n}<small>${n*state.multiplier}</small></button>`).join('')}</div><div class="specials"><button data-special="MISS">MISS</button><button data-special="25">25 <small>OUTER</small></button><button class="bull" data-special="BULL">BULL <small>50</small></button><button class="clear-current" ${!state.game.current.length?'disabled':''}>× Последний</button></div>`;}
function desktopVisitInput(){const p=activePlayer();return `<div class="desktop-keyboard-entry"><label class="desktop-score-box" for="visit-desktop"><span class="score-box-label">СУММА ПОДХОДА</span><input class="desktop-score-input" id="visit-desktop" inputmode="numeric" autocomplete="off" autofocus value="${state.visitValue}" placeholder="0–180" maxlength="3"><span class="keyboard-caret">|</span></label><div class="entry-preview desktop-preview">${visitPreview()}</div><div class="desktop-enter-bar"><kbd>ENTER</kbd><strong>Записать подход</strong><span>↵</span></div><div class="keyboard-hint"><kbd>0–9</kbd><span>введите сумму</span><kbd>Enter</kbd><span>подтвердить</span><kbd>Ctrl Z</kbd><span>отменить</span><kbd>Ctrl ⇧ Z</kbd><span>вернуть</span></div><div class="current-player-note"><span style="background:${p?.color||'#e83f5b'}"></span>Сейчас бросает <b>${esc(p?.name||'')}</b></div></div>`;}
function mobileGame(){const g=state.game,p=activePlayer(),view=displayPlayer();if(!g||!p||!view)return'';if(g.winner)return `<section class="mobile-game"><div class="m-winner"><span>ПОБЕДИТЕЛЬ МАТЧА</span><h1>${esc(g.players.find(x=>x.id===g.winner)?.name||'')}</h1><div class="winner-score">${winnerScoreline(g)}</div><button class="primary play-again">↻ Сыграть ещё</button></div></section>`;
 const preview=!!previewPlayer(),rem=preview?view.score:remaining(),quick=[26,45,60,81,100,140,180],count=g.players.length;return `<section class="mobile-game players-count-${count} ${preview?'is-previewing':''}"><div class="mobile-scoreboard players-${count}">${playerCards(true)}</div><div class="m-hero ${preview?'preview-hero':''}"><div class="m-turn"><span style="background:${view.color}"></span>${esc(view.name)} · ${preview?'ПРОСМОТР':'ХОД'}</div><small>${preview?'СЧЁТ ИГРОКА':'ОСТАЛОСЬ'}</small><strong>${Math.max(0,rem)}</strong><div class="m-darts">${preview?'3 ДРОТИКА · ВЫХОД':g.current.length?g.current.map(h=>h.label).join(' · '):'3 ДРОТИКА'}</div>${preview?`<div class="m-preview-live"><span class="live-turn-pill">ХОД: <b>${esc(p.name)}</b> · ${p.score}</span><button class="clear-preview m-back-turn">↩ Вернуться</button></div>`:nextTurnMarkup(true)}</div>${adviceMarkup(true,rem,preview)}<div class="m-entry-v3"><button class="undo-mobile icon-only" ${!state.undo.length?'disabled':''}>↶</button><div class="m-value-wrap"><div class="m-value ${state.visitValue?'filled':''}">${state.visitValue||'0–180'}</div><div class="entry-preview">${preview?`<span>ввод для <b>${esc(p.name)}</b></span>`:visitPreview()}</div></div><button class="redo-mobile icon-only" ${!state.redo.length?'disabled':''}>↷</button></div><div class="quick-row">${quick.map(v=>`<button data-quick="${v}">${v}</button>`).join('')}</div><div class="keypad">${['1','2','3','4','5','6','7','8','9','back','0','ok'].map(k=>`<button data-key="${k}" class="${k==='ok'?'key-ok':k==='back'?'key-back':''}">${k==='back'?'⌫':k==='ok'?'OK':k}</button>`).join('')}</div></section>`;}
function gameView(){if(!state.game)return `<section class="empty-state"><div>◎</div><h1>Матч ещё не начат</h1><p>Добавь игроков и выбери 301, 501 или свой режим.</p><button class="primary" data-nav="setup">Новая игра</button></section>`;return desktopGame()+mobileGame();}
function checkoutTable(){const q=Number(state.search),scores=Array.from({length:110},(_,i)=>170-i).filter(s=>!state.search||s===q);return `<section class="table-page"><div class="page-heading"><span class="kicker">61—170</span><h1>Таблица закрытий</h1><p>Основной маршрут и запасные варианты. Утроения готовят, удвоения закрывают.</p><input id="checkout-search" inputmode="numeric" placeholder="Найти остаток" value="${esc(state.search)}"></div><div class="legend"><span><i class="t"></i> утроение</span><span><i class="d"></i> удвоение</span><span><i class="b"></i> Bull</span></div><div class="checkout-grid">${scores.map(score=>{const rs=checkoutRoutes(score,3,3),bad=BOGEY.has(score)||!rs.length;return `<article class="checkout-card ${bad?'impossible':''}"><div class="checkout-number">${score}</div>${bad?'<div><strong>Нет закрытия</strong><small>Подготовь следующий подход</small></div>':`<div class="routes">${rs.map((r,i)=>`<div class="${i?'alt-route':'main-route'}"><small>${i?'ВАРИАНТ':'ОСНОВНОЙ'}</small><span>${r.map(h=>`<b class="${h.isTreble?'treble':h.isDouble?'double':h.label==='BULL'?'bull-hit':''}">${h.label}</b>`).join('')}</span></div>`).join('')}</div>`}</article>`;}).join('')}</div></section>`;}
function statsView(){const g=state.game;if(!g)return `<section class="empty-state"><div>◎</div><h1>Нет статистики</h1><p>Сначала начни матч.</p><button class="primary" data-nav="setup">Новая игра</button></section>`;return `<section class="stats-page"><div class="page-heading"><span class="kicker">ТЕКУЩИЙ МАТЧ</span><h1>Статистика</h1></div><div class="stats-grid">${g.players.map(p=>`<article class="stat-card panel" style="--player:${p.color}"><span class="player-bar"></span><h2>${esc(p.name)}</h2><strong>${p.darts?(p.total/p.darts*3).toFixed(2):'0.00'}<small>средний набор</small></strong><div><span><b>${p.high}</b>лучший подход</span><span><b>${p.darts}</b>дротиков</span><span><b>${p.wins}</b>легов</span><span><b>${g.history.filter(v=>v.playerId===p.id&&v.total===180&&!v.bust).length}</b>180</span></div></article>`).join('')}</div></section>`;}
function confirmModal(){if(!state.checkoutConfirm)return'';const d=state.checkoutConfirm;return `<div class="modal-backdrop"><div class="checkout-modal panel checkout-double-modal"><span class="kicker">DOUBLE OUT</span><h2>Чем закрыли ${d.value}?</h2><p>Выберите последнее удвоение. Оно сохранится в истории и статистике матча.</p><div class="double-grid">${d.doubles.map((label,i)=>`<button class="double-choice ${label===d.selected?'recommended':''}" data-select-double="${label}"><b>${label}</b>${i===0?'<small>РЕКОМЕНДУЕТСЯ</small>':''}</button>`).join('')}</div><div class="checkout-darts-label">ДРОТИКОВ В ЗАКРЫТИИ</div><div class="checkout-darts">${validCheckoutDartCounts(d.value,d.selected).map(n=>`<button class="${Number(d.darts)===n?'active':''}" data-checkout-darts="${n}">${n}</button>`).join('')}</div><button class="confirm-selected-double">ЗАКРЫТО · ${d.selected}</button><button class="confirm-bust">Не закрыли — BUST</button><button class="cancel-confirm">Отмена</button></div></div>`;}
function settingsPanel(){if(!state.settingsOpen)return'';const wakeSupported='wakeLock' in navigator;return `<div class="modal-backdrop settings-backdrop"><section class="settings-panel panel"><div class="settings-head"><div><span class="kicker">CHECKOUT LAB 1.0</span><h2>Настройки матча</h2></div><button class="close-settings">×</button></div><button class="setting-row sound-toggle"><span><b>Звук событий</b><small>Подход, 180, BUST, LEG</small></span><em>${state.sound?'ВКЛ':'ВЫКЛ'}</em></button><button class="setting-row vibration-toggle"><span><b>Вибрация</b><small>Короткий отклик на телефоне</small></span><em>${state.vibration?'ВКЛ':'ВЫКЛ'}</em></button><button class="setting-row wake-toggle"><span><b>Экран не гаснет</b><small>${wakeSupported?'Активно во время матча':'Не поддерживается браузером'}</small></span><em>${state.wakeLock?'ВКЛ':'ВЫКЛ'}</em></button>${state.game?'<button class="setting-row focus-toggle"><span><b>Режим у мишени</b><small>Полный экран, минимум браузерных элементов</small></span><em>⛶</em></button>':''}</section></div>`;}
function editLastModal(){if(!state.editLastOpen||!state.game?.history.length)return'';const base=rebuildGame(state.game.history.slice(0,-1)),p=base?.players[base.active],v=Number(state.editLastValue||0),left=p?p.score-v:null,valid=left===0?validFinishDoubles(v):[];if(left===0&&valid.length&&!valid.some(d=>d.label===state.editLastDouble))state.editLastDouble=valid[0].label;const editCounts=left===0&&state.editLastDouble?validCheckoutDartCounts(v,state.editLastDouble):[];if(editCounts.length&&!editCounts.includes(Number(state.editLastDarts)))state.editLastDarts=editCounts[0];return `<div class="modal-backdrop"><div class="checkout-modal panel edit-visit-modal"><span class="kicker">ПОСЛЕДНИЙ ПОДХОД</span><h2>Исправить результат</h2><p>${p?`${esc(p.name)} · было ${state.game.history.at(-1).total}`:''}</p><input id="edit-last-value" inputmode="numeric" maxlength="3" value="${esc(state.editLastValue)}" aria-label="Новая сумма">${!isPossibleVisitTotal(v)?`<div class="edit-error">${v} нельзя набрать за 3 дротика</div>`:''}${left===0&&valid.length?`<div class="edit-double-label">Последнее удвоение</div><div class="double-grid compact">${valid.map((d,i)=>`<button class="edit-double-choice ${d.label===state.editLastDouble?'recommended':''}" data-edit-double="${d.label}">${d.label}${i===0?'<small>РЕК.</small>':''}</button>`).join('')}</div><div class="checkout-darts-label">ДРОТИКОВ В ЗАКРЫТИИ</div><div class="checkout-darts">${editCounts.map(n=>`<button class="${Number(state.editLastDarts)===n?'active':''}" data-edit-darts="${n}">${n}</button>`).join('')}</div>`:''}<button class="save-edit" ${!isPossibleVisitTotal(v)?'disabled':''}>Сохранить</button><button class="delete-last">Удалить подход</button><button class="cancel-edit">Отмена</button></div></div>`;}


function render(){
 document.documentElement.dataset.theme=state.theme;document.body.className=`${state.screen==='game'?'game-screen ':''}${state.focusMode?'focus-mode':''}`.trim();
 const content=state.screen==='setup'?setupView():state.screen==='game'?gameView():state.screen==='checkouts'?checkoutTable():statsView();
 document.getElementById('app').innerHTML=`<main class="app ${state.theme==='light'?'light':''}">${header()}${mobileMenu()}${content}${historyDrawer()}${momentOverlay()}${confirmModal()}${settingsPanel()}${editLastModal()}</main>`;bind();syncWakeLock();
 if(state.screen==='game'&&state.game?.players.length>=5&&window.matchMedia?.('(max-width:768px)').matches){requestAnimationFrame(()=>document.querySelector('.mobile-scoreboard .m-player.active')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}));}
}
function bind(){
 document.querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>nav(el.dataset.nav));
 document.querySelectorAll('[data-table-link]').forEach(el=>el.onclick=()=>{location.href='./checkout-table.html';});
 document.querySelectorAll('.theme-toggle').forEach(el=>el.onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();render();});
 const mm=document.querySelector('.mobile-menu-button');if(mm)mm.onclick=()=>{state.mobileMenu=!state.mobileMenu;render();};document.querySelector('.settings-toggle')?.addEventListener('click',()=>{state.settingsOpen=true;render();});document.querySelector('.close-settings')?.addEventListener('click',()=>{state.settingsOpen=false;render();});document.querySelector('.settings-backdrop')?.addEventListener('click',e=>{if(e.target.classList.contains('settings-backdrop')){state.settingsOpen=false;render();}});document.querySelectorAll('.sound-toggle').forEach(el=>el.onclick=()=>{state.sound=!state.sound;save();render();});document.querySelectorAll('.vibration-toggle').forEach(el=>el.onclick=()=>{state.vibration=!state.vibration;save();render();});document.querySelectorAll('.wake-toggle').forEach(el=>el.onclick=()=>{state.wakeLock=!state.wakeLock;save();render();});document.querySelectorAll('.focus-toggle').forEach(el=>el.onclick=toggleFocusMode);
 document.querySelectorAll('[data-mode]').forEach(el=>el.onclick=()=>{state.mode=Number(el.dataset.mode);render();});
 document.querySelectorAll('.player-name').forEach(el=>el.oninput=e=>{state.names[Number(el.dataset.index)]=e.target.value;save();});
 document.querySelectorAll('.remove-player').forEach(el=>el.onclick=()=>{state.names.splice(Number(el.dataset.index),1);render();});
 document.querySelector('.add-player')?.addEventListener('click',()=>{state.names.push(`Игрок ${state.names.length+1}`);render();});
 document.querySelector('.start-button')?.addEventListener('click',()=>{const cs=document.getElementById('custom-score');if(cs)state.customScore=Number(cs.value);const ls=document.getElementById('legs-select');if(ls)state.legs=Number(ls.value);document.querySelectorAll('.player-name').forEach(el=>state.names[Number(el.dataset.index)]=el.value);startGame();});
 document.getElementById('custom-score')?.addEventListener('change',e=>{state.customScore=Number(e.target.value);save();});
 document.getElementById('legs-select')?.addEventListener('change',e=>{state.legs=Number(e.target.value);save();});
 document.querySelectorAll('[data-input]').forEach(el=>el.onclick=()=>{state.inputMode=el.dataset.input;render();});
 document.querySelectorAll('[data-mult]').forEach(el=>el.onclick=()=>{state.multiplier=Number(el.dataset.mult);render();});
 document.querySelectorAll('[data-dart]').forEach(el=>el.onclick=()=>{const n=Number(el.dataset.dart),prefix=state.multiplier===1?'S':state.multiplier===2?'D':'T';addDart(byLabel[`${prefix}${n}`]);});
 document.querySelectorAll('[data-special]').forEach(el=>el.onclick=()=>addDart(byLabel[el.dataset.special]||MISS));
 document.querySelector('.clear-current')?.addEventListener('click',()=>{if(!state.game?.current.length)return;snapshot();state.game.current.pop();save();render();});
 document.querySelectorAll('.undo,.undo-mobile').forEach(el=>el.onclick=undo);document.querySelectorAll('.redo,.redo-mobile').forEach(el=>el.onclick=redo);
 document.querySelectorAll('[data-preview-player]').forEach(el=>{const select=()=>{const id=el.dataset.previewPlayer;const active=activePlayer();state.previewPlayerId=active?.id===id?null:(state.previewPlayerId===id?null:id);render();};el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};});document.querySelectorAll('.clear-preview').forEach(el=>el.onclick=()=>{state.previewPlayerId=null;render();});
 const vi=document.getElementById('visit-desktop');if(vi){vi.oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,3);if(Number(v)>180)v='180';state.visitValue=v;state.inputError='';e.target.value=v;const preview=document.querySelector('.desktop-preview');if(preview)preview.innerHTML=visitPreview();const submit=document.querySelector('.desktop-submit');if(submit)submit.disabled=v==='';};vi.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();requestVisitSubmit();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}};setTimeout(()=>vi.focus({preventScroll:true}),0);}
 document.querySelector('.submit-visit')?.addEventListener('click',requestVisitSubmit);
 document.querySelectorAll('[data-key]').forEach(el=>el.onclick=()=>keypad(el.dataset.key));document.querySelectorAll('[data-quick]').forEach(el=>el.onclick=()=>quick(el.dataset.quick));
 document.querySelector('.open-history')?.addEventListener('click',()=>{state.historyOpen=true;render();});document.querySelectorAll('.close-history').forEach(el=>el.addEventListener('click',()=>{state.historyOpen=false;render();}));
 document.querySelectorAll('.play-again').forEach(el=>el.onclick=startGame);
 document.querySelectorAll('[data-select-double]').forEach(el=>el.onclick=()=>{state.checkoutConfirm.selected=el.dataset.selectDouble;const counts=validCheckoutDartCounts(state.checkoutConfirm.value,state.checkoutConfirm.selected);state.checkoutConfirm.darts=counts[0]||3;render();});document.querySelectorAll('[data-checkout-darts]').forEach(el=>el.onclick=()=>{state.checkoutConfirm.darts=Number(el.dataset.checkoutDarts);render();});document.querySelector('.confirm-selected-double')?.addEventListener('click',()=>confirmCheckout(state.checkoutConfirm.selected));document.querySelector('.confirm-bust')?.addEventListener('click',()=>{const value=state.checkoutConfirm?.value;if(value==null)return;state.checkoutConfirm=null;finishVisit([{label:`Σ${value}`,value,multiplier:1,number:value,isDouble:false,isTreble:false}],true,3);});document.querySelector('.cancel-confirm')?.addEventListener('click',cancelCheckout);document.querySelectorAll('[data-edit-last]').forEach(el=>el.onclick=openEditLast);document.querySelector('.cancel-edit')?.addEventListener('click',()=>{state.editLastOpen=false;state.inputError='';render();});document.querySelector('.delete-last')?.addEventListener('click',deleteLastVisit);document.querySelector('.save-edit')?.addEventListener('click',applyEditedLastVisit);document.querySelectorAll('[data-edit-double]').forEach(el=>el.onclick=()=>{state.editLastDouble=el.dataset.editDouble;const counts=validCheckoutDartCounts(Number(state.editLastValue),state.editLastDouble);state.editLastDarts=counts[0]||3;render();});document.querySelectorAll('[data-edit-darts]').forEach(el=>el.onclick=()=>{state.editLastDarts=Number(el.dataset.editDarts);render();});const editInput=document.getElementById('edit-last-value');if(editInput){editInput.oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,3);if(Number(v)>180)v='180';state.editLastValue=v;render();};setTimeout(()=>document.getElementById('edit-last-value')?.focus(),0);}
 document.onkeydown=e=>{if(state.screen!=='game'||window.matchMedia?.('(max-width:768px)').matches||state.checkoutConfirm!==null)return;const input=document.getElementById('visit-desktop');if(!input)return;if(document.activeElement!==input){if(/^\d$/.test(e.key)){e.preventDefault();input.focus();const next=(state.visitValue+e.key).replace(/^0+(?=\d)/,'').slice(0,3);if(Number(next)<=180){state.visitValue=next;input.value=next;input.dispatchEvent(new Event('input',{bubbles:true}));}}else if(e.key==='Enter'&&state.visitValue!==''){e.preventDefault();requestVisitSubmit();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.key==='Escape'&&state.focusMode){e.preventDefault();toggleFocusMode();}}};
 const search=document.getElementById('checkout-search');if(search)search.oninput=e=>{state.search=e.target.value.replace(/\D/g,'').slice(0,3);render();setTimeout(()=>document.getElementById('checkout-search')?.focus(),0);};
}

if(globalThis.__CHECKOUT_LAB_TEST__)globalThis.__CL_TEST__={state,checkoutRoutes,isPossibleVisitTotal,validFinishDoubles,validCheckoutDartCounts,rebuildGame,applyRecordedVisit,startGame,requestVisitSubmit,confirmCheckout,undo,redo,openEditLast,applyEditedLastVisit,deleteLastVisit};
load();render();
document.addEventListener('visibilitychange',()=>syncWakeLock());document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&state.focusMode){state.focusMode=false;save();render();}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
