(() => {
'use strict';
const root=document.getElementById('onlineApp');const isEn=location.pathname.startsWith('/en/');
const T={
 ru:{loading:'Загрузка…',notConfigured:'Online почти готов',needCfg:'Подключи Project URL и Publishable key Supabase — после этого этот экран заработает без изменения логики.',login:'Войти',signup:'Регистрация',email:'E-mail',pass:'Пароль',name:'Имя',profile:'Профиль',logout:'Выйти',create:'Создать онлайн-матч',join:'Войти по коду',room:'Комната',game:'Игра',legs:'Легов для победы',double:'Double Out',waiting:'Ждём второго игрока',copy:'Скопировать код',share:'Скопировать ссылку другу',copied:'Ссылка скопирована',score:'Сумма подхода',darts:'Дротиков',checkout:'Последнее удвоение',notCheckout:'Не закрытие',send:'ЗАПИСАТЬ ПОДХОД',turn:'ХОД',yourTurn:'ВАШ ХОД',opponentTurn:'ХОД СОПЕРНИКА',finished:'МАТЧ ЗАВЕРШЁН',history:'Последние подходы',back:'В лобби',error:'Ошибка',online:'Онлайн',connecting:'Подключение',fallback:'Резервная синхронизация',username:'Ник',save:'Сохранить профиль'},
 en:{loading:'Loading…',notConfigured:'Online is almost ready',needCfg:'Connect the Supabase Project URL and Publishable key — then this screen works without changing the game logic.',login:'Sign in',signup:'Create account',email:'Email',pass:'Password',name:'Name',profile:'Profile',logout:'Sign out',create:'Create online match',join:'Join by code',room:'Room',game:'Game',legs:'Legs to win',double:'Double Out',waiting:'Waiting for player two',copy:'Copy code',share:'Copy invite link',copied:'Invite link copied',score:'Visit score',darts:'Darts',checkout:'Finishing double',notCheckout:'Not a checkout',send:'SUBMIT VISIT',turn:'TURN',yourTurn:'YOUR TURN',opponentTurn:"OPPONENT'S TURN",finished:'MATCH FINISHED',history:'Recent visits',back:'Lobby',error:'Error',online:'Online',connecting:'Connecting',fallback:'Fallback sync',username:'Username',save:'Save profile'}
}[isEn?'en':'ru'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let snapshot=null,msg='';
const syncLabel=status=>status==='SUBSCRIBED'?T.online:status==='CONNECTING'?T.connecting:T.fallback;
function setMsg(s){msg=s;render()}
function authView(){
 return '<section class="ol-card"><h1>Checkout Lab <span style="color:var(--green)">Online</span></h1><p class="muted">'+(isEn?'Play 301/501 live from different locations.':'Играйте 301/501 в реальном времени из разных мест.')+'</p><div class="grid"><form id="loginForm" class="stack"><h2>'+T.login+'</h2><input name="email" type="email" placeholder="'+T.email+'" required><input name="password" type="password" placeholder="'+T.pass+'" minlength="6" required><button class="primary">'+T.login+'</button></form><form id="signupForm" class="stack"><h2>'+T.signup+'</h2><input name="displayName" placeholder="'+T.name+'" required><input name="email" type="email" placeholder="'+T.email+'" required><input name="password" type="password" placeholder="'+T.pass+'" minlength="6" required><button class="primary">'+T.signup+'</button></form></div>'+status()+'</section>'
}
function status(){return msg?'<p class="status '+(msg.startsWith('✓')?'ok':'err')+'">'+esc(msg)+'</p>':''}
function lobby(){
 const p=snapshot.profile||{};return '<div class="topbar"><div><span class="pill">'+T.online+'</span><h1>'+esc(p.display_name||p.username)+'</h1><p class="muted">@'+esc(p.username)+'</p></div><button id="logout" class="secondary">'+T.logout+'</button></div><div class="grid"><section class="ol-card stack"><h2>'+T.create+'</h2><label>'+T.game+'<select id="gameType"><option>501</option><option>301</option></select></label><label>'+T.legs+'<select id="legs"><option>1</option><option>2</option><option>3</option><option>5</option><option>7</option></select></label><label class="row"><input id="doubleOut" type="checkbox" checked style="width:auto"> '+T.double+'</label><button id="createMatch" class="primary">'+T.create+'</button></section><section class="ol-card stack"><h2>'+T.join+'</h2><input id="roomCode" maxlength="6" placeholder="ABC123" style="text-transform:uppercase;font-size:28px;font-weight:1000;letter-spacing:.12em"><button id="joinMatch" class="primary">'+T.join+'</button><hr style="width:100%;border:0;border-top:1px solid var(--line)"><h3>'+T.profile+'</h3><input id="username" value="'+esc(p.username||'')+'" placeholder="'+T.username+'"><input id="displayName" value="'+esc(p.display_name||'')+'" placeholder="'+T.name+'"><button id="saveProfile" class="secondary">'+T.save+'</button></section></div>'+status()
}
function matchView(){
 const m=snapshot.match,ps=snapshot.players||[];const waiting=ps.length<2;
 const playerName=p=>p?.profiles?.display_name||p?.profiles?.username||'Player';
 const active=ps.find(p=>p.user_id===m.current_player_id)||ps[0];
 const cards=(mobile=false)=>ps.map((p,i)=>'<div class="online-player '+(mobile?'mobile-player ':'')+(m.current_player_id===p.user_id?'active':'')+'" style="--player:'+(i?'#f7b844':'#43d08a')+'"><span class="player-line"></span><div><strong>'+esc(playerName(p))+'</strong><small>'+(m.current_player_id===p.user_id?T.turn+' · ':'')+'LEGS '+p.legs_won+' / '+m.legs_to_win+'</small></div><b>'+p.remaining+'</b></div>').join('');
 const mine=m.current_player_id===snapshot.user?.id&&m.status==='live';
 const hist=(snapshot.visits||[]).map(v=>'<div class="visit"><span>'+esc((ps.find(p=>p.user_id===v.user_id)?.profiles?.display_name)||'Player')+'</span><b>'+v.score+(v.bust?' BUST':'')+'</b><span>'+v.remaining_before+' → '+v.remaining_after+'</span></div>').join('');
 const doubles='<option value="">'+T.notCheckout+'</option>'+Array.from({length:20},(_,i)=>'<option value="'+(i+1)+'">D'+(i+1)+'</option>').join('')+'<option value="25">BULL</option>';
 const controls=prefix=>'<div class="online-controls"><label>'+T.darts+'<select data-darts><option value="3">3</option><option value="2">2</option><option value="1">1</option></select></label>'+(m.double_out?'<label>'+T.checkout+'<select data-double>'+doubles+'</select></label>':'')+'</div>';
 const desktop='<section class="online-desktop-game"><aside class="online-players panel"><div class="online-panel-title">◉ '+(isEn?'PLAYERS':'ИГРОКИ')+'</div>'+cards()+'<div class="online-room-mini"><span>'+T.room+'</span><b>'+m.room_code+'</b><small>'+esc(syncLabel(snapshot.realtimeStatus))+'</small></div></aside><section class="online-stage panel"><div class="online-stage-head"><div><small>'+(isEn?'NOW THROWING':'СЕЙЧАС БРОСАЕТ')+'</small><strong>'+esc(playerName(active))+'</strong></div><span>'+m.game_type+' · '+(m.double_out?'DOUBLE OUT':'STRAIGHT OUT')+'</span></div><div class="online-score-ring"><small>'+(isEn?'REMAINING':'ОСТАЛОСЬ')+'</small><strong>'+Math.max(0,active?.remaining||0)+'</strong><span>3 '+T.darts.toUpperCase()+'</span></div><div class="online-turn-state '+(mine?'mine':'')+'">'+(mine?'● '+T.yourTurn:T.opponentTurn)+'</div></section><aside class="online-entry panel"><div class="online-entry-head"><span>'+T.score+'</span><strong>'+(mine?(isEn?'Enter score':'Введите сумму'):(isEn?'Waiting for opponent':'Ожидаем соперника'))+'</strong></div>'+(mine?'<div class="online-score-box"><input data-online-score inputmode="numeric" autocomplete="off" maxlength="3" placeholder="0–180" aria-label="'+T.score+'"></div>'+controls('desktop')+'<button data-submit-visit class="primary online-submit">'+T.send+' <span>↵</span></button>':'')+'<div class="online-history"><h3>◷ '+T.history+'</h3><div>'+hist+'</div></div></aside></section>';
 const keys=['1','2','3','4','5','6','7','8','9','back','0','ok'].map(k=>'<button data-key="'+k+'" class="'+(k==='ok'?'key-ok':k==='back'?'key-back':'')+'" '+(!mine?'disabled':'')+'>'+(k==='back'?'⌫':k==='ok'?'OK':k)+'</button>').join('');
 const mobile='<section class="online-mobile-game"><div class="online-mobile-top"><div><span>'+T.room+'</span><b>'+m.room_code+'</b></div><small>'+esc(syncLabel(snapshot.realtimeStatus))+'</small></div><div class="online-mobile-players">'+cards(true)+'</div><div class="online-mobile-hero panel"><div>'+esc(playerName(active))+' · '+T.turn+'</div><small>'+(isEn?'REMAINING':'ОСТАЛОСЬ')+'</small><strong>'+Math.max(0,active?.remaining||0)+'</strong><span class="'+(mine?'mine':'')+'">'+(mine?'● '+T.yourTurn:T.opponentTurn)+'</span></div><div class="online-mobile-entry"><input data-online-score inputmode="numeric" readonly placeholder="0–180" aria-label="'+T.score+'">'+controls('mobile')+'</div><div class="online-keypad">'+keys+'</div></section>';
 return '<div class="online-match-actions"><button id="lobby" class="secondary">'+T.back+'</button></div>'+(!waiting?desktop+mobile:'<section class="ol-card waiting-card"><div class="room-label">'+T.room+'</div><div class="room-code">'+m.room_code+'</div><h2>'+T.waiting+'</h2><div class="row"><button id="copyCode" class="secondary">'+T.copy+'</button><button id="shareLink" class="primary">'+T.share+'</button></div></section>')+(m.status==='finished'?'<h2 class="online-finished">'+T.finished+'</h2>':'')+status()
}
function render(){
 if(!snapshot){root.innerHTML='<section class="ol-card"><h1>'+T.loading+'</h1></section>';return}
 if(!snapshot.client){root.innerHTML='<section class="ol-card"><h1>'+T.notConfigured+'</h1><p class="muted">'+T.needCfg+'</p></section>';return}
 root.innerHTML=!snapshot.user?authView():snapshot.match?matchView():lobby();bind()
}
function bind(){
 document.getElementById('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await CheckoutOnline.signIn(f.get('email'),f.get('password'));setMsg('✓ OK')}catch(x){setMsg(x.message)}})
 document.getElementById('signupForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await CheckoutOnline.signUp(f.get('email'),f.get('password'),f.get('displayName'));setMsg('✓ '+(isEn?'Check your email if confirmation is enabled.':'Если включено подтверждение, проверьте почту.'))}catch(x){setMsg(x.message)}})
 document.getElementById('logout')?.addEventListener('click',()=>CheckoutOnline.signOut().catch(x=>setMsg(x.message)))
 document.getElementById('createMatch')?.addEventListener('click',async()=>{try{await CheckoutOnline.createMatch({gameType:+document.getElementById('gameType').value,legsToWin:+document.getElementById('legs').value,doubleOut:document.getElementById('doubleOut').checked})}catch(x){setMsg(x.message)}})
 document.getElementById('joinMatch')?.addEventListener('click',async()=>{try{await CheckoutOnline.joinMatch(document.getElementById('roomCode').value)}catch(x){setMsg(x.message)}})
 document.getElementById('saveProfile')?.addEventListener('click',async()=>{try{await CheckoutOnline.updateProfile({username:document.getElementById('username').value,display_name:document.getElementById('displayName').value});setMsg('✓ OK')}catch(x){setMsg(x.message)}})
 const scoreInputs=[...document.querySelectorAll('[data-online-score]')];
 const setScore=value=>scoreInputs.forEach(input=>{input.value=value});
 const cleanScore=value=>{const clean=String(value||'').replace(/\D/g,'').slice(0,3);return clean&&Number(clean)>180?'180':clean};
 scoreInputs.forEach(input=>{input.addEventListener('input',()=>setScore(cleanScore(input.value)));input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();input.closest('.online-entry')?.querySelector('[data-submit-visit]')?.click()}})});
 document.querySelectorAll('[data-key]').forEach(button=>button.addEventListener('click',()=>{const current=scoreInputs[0]?.value||'';const key=button.dataset.key;if(key==='back')setScore(current.slice(0,-1));else if(key==='ok')submitOnlineVisit(button.closest('.online-mobile-game'),button);else setScore(cleanScore(current+key))}));
 document.querySelectorAll('[data-submit-visit]').forEach(button=>button.addEventListener('click',()=>submitOnlineVisit(button.closest('.online-entry'),button)));
 if(snapshot?.match&&!window.matchMedia('(max-width:768px)').matches){
  const desktopScore=document.querySelector('.online-desktop-game [data-online-score]');desktopScore?.focus({preventScroll:true});
  document.onkeydown=e=>{if(e.ctrlKey||e.metaKey||e.altKey||document.querySelector('[role="dialog"]'))return;if(/^\d$/.test(e.key)&&document.activeElement!==desktopScore){e.preventDefault();setScore(cleanScore((desktopScore?.value||'')+e.key));desktopScore?.focus({preventScroll:true})}else if(e.key==='Enter'&&desktopScore?.value){e.preventDefault();document.querySelector('.online-desktop-game [data-submit-visit]')?.click()}}
 }else document.onkeydown=null;
 document.getElementById('copyCode')?.addEventListener('click',()=>navigator.clipboard.writeText(snapshot.match.room_code))
 document.getElementById('shareLink')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(CheckoutOnline.inviteUrl());setMsg('✓ '+T.copied)})
 document.getElementById('lobby')?.addEventListener('click',()=>CheckoutOnline.leaveMatch().catch(x=>setMsg(x.message)))
}
async function submitOnlineVisit(scope,button){
 try{button.disabled=true;const score=+document.querySelector('[data-online-score]')?.value;if(!Number.isInteger(score)||score<0||score>180)throw new Error('0–180');const raw=scope?.querySelector('[data-double]')?.value;const darts=scope?.querySelector('[data-darts]')?.value||3;await CheckoutOnline.submitVisit(score,{dartsUsed:+darts,checkoutDouble:raw?+raw:null})}catch(x){setMsg(x.message)}finally{button.disabled=false}
}
document.getElementById('langBtn').addEventListener('click',()=>{location.href=isEn?'../online.html':'./en/online.html'});
CheckoutOnline.subscribe(s=>{snapshot=s;render()});CheckoutOnline.init().catch(e=>{snapshot={...CheckoutOnline.state};setMsg(e.message)});
})();
