(() => {
'use strict';
const root=document.getElementById('onlineApp');const isEn=location.pathname.startsWith('/en/');
const T={
 ru:{loading:'Загрузка…',notConfigured:'Online почти готов',needCfg:'Подключи Project URL и Publishable key Supabase — после этого этот экран заработает без изменения логики.',login:'Войти',signup:'Регистрация',email:'E-mail',pass:'Пароль',name:'Имя',profile:'Профиль',logout:'Выйти',create:'Создать онлайн-матч',join:'Войти по коду',room:'Комната',game:'Игра',legs:'Легов для победы',double:'Double Out',waiting:'Ждём второго игрока',copy:'Скопировать код',share:'Скопировать ссылку другу',copied:'Ссылка скопирована',score:'Сумма подхода',darts:'Дротиков',checkout:'Последнее удвоение',notCheckout:'Не закрытие',send:'ЗАПИСАТЬ ПОДХОД',turn:'ХОД',yourTurn:'ВАШ ХОД',opponentTurn:'ХОД СОПЕРНИКА',finished:'МАТЧ ЗАВЕРШЁН',history:'Последние подходы',back:'В лобби',error:'Ошибка',online:'Онлайн',connecting:'Подключение',fallback:'Резервная синхронизация',username:'Ник',save:'Сохранить профиль'},
 en:{loading:'Loading…',notConfigured:'Online is almost ready',needCfg:'Connect the Supabase Project URL and Publishable key — then this screen works without changing the game logic.',login:'Sign in',signup:'Create account',email:'Email',pass:'Password',name:'Name',profile:'Profile',logout:'Sign out',create:'Create online match',join:'Join by code',room:'Room',game:'Game',legs:'Legs to win',double:'Double Out',waiting:'Waiting for player two',copy:'Copy code',share:'Copy invite link',copied:'Invite link copied',score:'Visit score',darts:'Darts',checkout:'Finishing double',notCheckout:'Not a checkout',send:'SUBMIT VISIT',turn:'TURN',yourTurn:'YOUR TURN',opponentTurn:"OPPONENT'S TURN",finished:'MATCH FINISHED',history:'Recent visits',back:'Lobby',error:'Error',online:'Online',connecting:'Connecting',fallback:'Fallback sync',username:'Username',save:'Save profile'}
}[isEn?'en':'ru'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const checkoutHits=[];for(let n=1;n<=20;n++)checkoutHits.push({label:'S'+n,value:n},{label:'D'+n,value:n*2,double:true},{label:'T'+n,value:n*3,treble:true});checkoutHits.push({label:'25',value:25},{label:'BULL',value:50,double:true,bull:true});
const finishHits=checkoutHits.filter(h=>h.double),routeCache=new Map(),preferredDoubles=['D20','D16','D18','D12','D10','D8','D14','D6','D4','D2','D1','BULL'];
function onlineCheckoutRoutes(score,limit=3){
 if(routeCache.has(score))return routeCache.get(score);if(score<2||score>170)return[];const routes=[];
 for(const f of finishHits)if(f.value===score)routes.push([f]);
 for(const a of checkoutHits)for(const f of finishHits)if(a.value+f.value===score)routes.push([a,f]);
 for(const a of checkoutHits)for(const b of checkoutHits)for(const f of finishHits)if(a.value+b.value+f.value===score)routes.push([a,b,f]);
 const normalized=routes.map(route=>{const start=route.slice(0,-1).sort((a,b)=>(b.treble?1:0)-(a.treble?1:0)||b.value-a.value);return [...start,route.at(-1)]});
 const unique=[...new Map(normalized.map(r=>[r.map(h=>h.label).join('-'),r])).values()];unique.sort((a,b)=>a.length-b.length||(preferredDoubles.indexOf(a.at(-1).label)+1||99)-(preferredDoubles.indexOf(b.at(-1).label)+1||99)||b.slice(0,-1).reduce((s,h)=>s+h.value,0)-a.slice(0,-1).reduce((s,h)=>s+h.value,0));
 const out=unique.slice(0,limit);routeCache.set(score,out);return out;
}
const routeHtml=route=>route.map(h=>'<b class="'+(h.treble?'treble':h.double?'double':h.bull?'bull-hit':'')+'">'+h.label+'</b>').join('<i>→</i>');
function checkoutAdvice(score,mobile=false){const routes=onlineCheckoutRoutes(score);if(!routes.length)return '<div class="online-checkout '+(mobile?'mobile':'')+' quiet"><span>'+(isEn?'NO CHECKOUT':'ЗАКРЫТИЯ НЕТ')+'</span><a href="'+(isEn?'./checkout-table.html':'./checkout-table.html')+'">'+(isEn?'TABLE 2–170':'ТАБЛИЦА 2–170')+'</a></div>';return '<div class="online-checkout '+(mobile?'mobile':'')+'"><span>'+(isEn?'CHECKOUT':'ВЫХОД НА ЗАКРЫТИЕ')+'</span><strong>'+routeHtml(routes[0])+'</strong><a href="'+(isEn?'./checkout-table.html':'./checkout-table.html')+'">'+(isEn?'TABLE 2–170':'ТАБЛИЦА 2–170')+'</a></div>'}
function validFinishDoubles(score){return finishHits.filter(f=>{const rest=score-f.value;if(rest===0)return true;if(rest<0)return false;if(checkoutHits.some(a=>a.value===rest))return true;return checkoutHits.some(a=>checkoutHits.some(b=>a.value+b.value===rest))}).sort((a,b)=>(preferredDoubles.indexOf(a.label)+1||99)-(preferredDoubles.indexOf(b.label)+1||99))}
function checkoutModal(){if(!pendingCheckout)return'';const options=pendingCheckout.doubles.map(hit=>'<button data-confirm-double="'+hit.value+'" class="double-choice">'+hit.label+'</button>').join('');return '<div class="online-modal-backdrop"><section class="online-checkout-modal panel" role="dialog" aria-modal="true" aria-label="'+(isEn?'Confirm checkout':'Подтвердить закрытие')+'"><span>DOUBLE OUT</span><h2>'+(isEn?'Finishing double':'Последнее удвоение')+'</h2><p>'+(isEn?'Choose only when the leg is actually finished.':'Выберите только если лег действительно закрыт.')+'</p><div class="online-double-grid">'+options+'</div><button data-checkout-bust class="secondary">'+(isEn?'Not finished — BUST':'Не закрыли — BUST')+'</button><button data-checkout-cancel class="ghost-modal">'+(isEn?'Cancel':'Отмена')+'</button></section></div>'}
let snapshot=null,msg='',pendingCheckout=null;
const syncLabel=status=>status==='SUBSCRIBED'?T.online:status==='CONNECTING'?T.connecting:T.fallback;
function setMsg(s){msg=s;render()}
function authView(){
 return '<section class="ol-card"><h1>Checkout Lab <span style="color:var(--green)">Online</span></h1><p class="muted">'+(isEn?'Play 301/501 live from different locations.':'Играйте 301/501 в реальном времени из разных мест.')+'</p><div class="grid"><form id="loginForm" class="stack"><h2>'+T.login+'</h2><input name="email" type="email" placeholder="'+T.email+'" required><input name="password" type="password" placeholder="'+T.pass+'" minlength="6" required><button class="primary">'+T.login+'</button></form><form id="signupForm" class="stack"><h2>'+T.signup+'</h2><input name="displayName" placeholder="'+T.name+'" required><input name="email" type="email" placeholder="'+T.email+'" required><input name="password" type="password" placeholder="'+T.pass+'" minlength="6" required><button class="primary">'+T.signup+'</button></form></div>'+status()+'</section>'
}
function status(){return msg?'<p class="status '+(msg.startsWith('✓')?'ok':'err')+'">'+esc(msg)+'</p>':''}
function lobby(){
 const p=snapshot.profile||{};return '<div class="topbar"><div><span class="pill">'+T.online+'</span><h1>'+esc(p.display_name||p.username)+'</h1><p class="muted">@'+esc(p.username)+'</p></div><button id="logout" class="secondary">'+T.logout+'</button></div><div class="grid"><section class="ol-card stack"><h2>'+T.create+'</h2><label>'+T.game+'<select id="gameType"><option>501</option><option>301</option></select></label><label>'+T.legs+'<select id="legs"><option>1</option><option>2</option><option>3</option><option>5</option><option>7</option></select></label><label class="row"><input id="doubleOut" type="checkbox" checked style="width:auto"> '+T.double+'</label><button id="createMatch" class="primary">'+T.create+'</button></section><section class="ol-card stack"><h2>'+T.join+'</h2><input id="roomCode" maxlength="6" placeholder="ABC123" style="text-transform:uppercase;font-size:28px;font-weight:1000;letter-spacing:.12em"><button id="joinMatch" class="primary">'+T.join+'</button><hr style="width:100%;border:0;border-top:1px solid var(--line)"><h3>'+T.profile+'</h3><input id="username" value="'+esc(p.username||'')+'" placeholder="'+T.username+'"><input id="displayName" value="'+esc(p.display_name||'')+'" placeholder="'+T.name+'"><button id="saveProfile" class="secondary">'+T.save+'</button></section></div>'+status()
}
function matchView(){
 const m=snapshot.match,ps=snapshot.players||[];const waiting=ps.length<2;
 const playerName=p=>p?.profiles?.display_name||p?.profiles?.username||'Player';
 const active=ps.find(p=>p.user_id===m.current_player_id)||ps[0];
 const cards=(mobile=false)=>ps.map((p,i)=>'<div class="online-player '+(mobile?'mobile-player ':'')+(m.current_player_id===p.user_id?'active':'')+'" style="--player:'+(i?'#f7b844':'#43d08a')+'"><span class="player-line"></span><div><strong>'+esc(playerName(p))+'</strong><small>'+(m.current_player_id===p.user_id?T.turn+' · ':'')+'LEGS '+p.legs_won+' / '+m.legs_to_win+'</small></div><b>'+p.remaining+'</b></div>').join('');
 const mine=m.current_player_id===snapshot.user?.id&&m.status==='live';
 const hist=(snapshot.visits||[]).map(v=>'<div class="visit"><span>'+esc((ps.find(p=>p.user_id===v.user_id)?.profiles?.display_name)||'Player')+'</span><b>'+v.score+(v.bust?' BUST':'')+'</b><span>'+v.remaining_before+' → '+v.remaining_after+'</span></div>').join('');
 const desktop='<section class="online-desktop-game"><aside class="online-players panel"><div class="online-panel-title">◉ '+(isEn?'PLAYERS':'ИГРОКИ')+'</div>'+cards()+'<div class="online-room-mini"><span>'+T.room+'</span><b>'+m.room_code+'</b><small>'+esc(syncLabel(snapshot.realtimeStatus))+'</small></div></aside><section class="online-stage panel"><div class="online-stage-head"><div><small>'+(isEn?'NOW THROWING':'СЕЙЧАС БРОСАЕТ')+'</small><strong>'+esc(playerName(active))+'</strong></div><span>'+m.game_type+' · '+(m.double_out?'DOUBLE OUT':'STRAIGHT OUT')+'</span></div><div class="online-score-ring"><small>'+(isEn?'REMAINING':'ОСТАЛОСЬ')+'</small><strong>'+Math.max(0,active?.remaining||0)+'</strong></div>'+checkoutAdvice(active?.remaining||0)+'<div class="online-turn-state '+(mine?'mine':'')+'">'+(mine?'● '+T.yourTurn:T.opponentTurn)+'</div></section><aside class="online-entry panel"><div class="online-entry-head"><span>'+T.score+'</span><strong>'+(mine?(isEn?'Enter score':'Введите сумму'):(isEn?'Waiting for opponent':'Ожидаем соперника'))+'</strong></div>'+(mine?'<div class="online-score-box"><input data-online-score inputmode="numeric" autocomplete="off" maxlength="3" placeholder="0–180" aria-label="'+T.score+'"></div><button data-submit-visit class="primary online-submit">'+T.send+' <span>↵</span></button>':'')+'<div class="online-history"><h3>◷ '+T.history+'</h3><div>'+hist+'</div></div></aside></section>';
 const keys=['1','2','3','4','5','6','7','8','9','back','0','ok'].map(k=>'<button data-key="'+k+'" class="'+(k==='ok'?'key-ok':k==='back'?'key-back':'')+'" '+(!mine?'disabled':'')+'>'+(k==='back'?'⌫':k==='ok'?'OK':k)+'</button>').join('');
 const mobile='<section class="online-mobile-game"><div class="online-mobile-top"><div><span>'+T.room+'</span><b>'+m.room_code+'</b></div><small>'+esc(syncLabel(snapshot.realtimeStatus))+'</small></div><div class="online-mobile-players">'+cards(true)+'</div><div class="online-mobile-hero panel"><div>'+esc(playerName(active))+' · '+T.turn+'</div><small>'+(isEn?'REMAINING':'ОСТАЛОСЬ')+'</small><strong>'+Math.max(0,active?.remaining||0)+'</strong><span class="'+(mine?'mine':'')+'">'+(mine?'● '+T.yourTurn:T.opponentTurn)+'</span></div>'+checkoutAdvice(active?.remaining||0,true)+'<div class="online-mobile-entry"><input data-online-score inputmode="numeric" readonly placeholder="0–180" aria-label="'+T.score+'"></div><div class="online-keypad">'+keys+'</div></section>';
 return '<div class="online-match-actions"><button id="lobby" class="secondary">'+T.back+'</button></div>'+(!waiting?desktop+mobile:'<section class="ol-card waiting-card"><div class="room-label">'+T.room+'</div><div class="room-code">'+m.room_code+'</div><h2>'+T.waiting+'</h2><div class="row"><button id="copyCode" class="secondary">'+T.copy+'</button><button id="shareLink" class="primary">'+T.share+'</button></div></section>')+(m.status==='finished'?'<h2 class="online-finished">'+T.finished+'</h2>':'')+status()+checkoutModal()
}
function render(){
 if(!snapshot){root.innerHTML='<section class="ol-card"><h1>'+T.loading+'</h1></section>';return}
 if(!snapshot.client){root.innerHTML='<section class="ol-card"><h1>'+T.notConfigured+'</h1><p class="muted">'+T.needCfg+'</p></section>';return}
 root.innerHTML=!snapshot.user?authView():snapshot.match?matchView():lobby();bind()
}
function bind(){
 document.getElementById('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await CheckoutOnline.signIn(f.get('email'),f.get('password'));setMsg('✓ OK')}catch(x){setMsg(x.message)}})
 document.getElementById('signupForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await CheckoutOnline.signUp(f.get('email'),f.get('password'),f.get('displayName'));setMsg('✓ '+(isEn?'Check your email if confirmation is enabled.':'Если включено подтверждение, проверьте почту.'))}catch(x){setMsg(x.message)}})
 document.getElementById('logout')?.addEventListener('click',()=>CheckoutOnline.signOut().catch(x=>setMsg(x.message)))
 document.getElementById('createMatch')?.addEventListener('click',async()=>{try{await CheckoutOnline.createMatch({gameType:+document.getElementById('gameType').value,legsToWin:+document.getElementById('legs').value,doubleOut:document.getElementById('doubleOut').checked})}catch(x){setMsg(x.message)}})
 document.getElementById('joinMatch')?.addEventListener('click',async()=>{try{await CheckoutOnline.joinMatch(document.getElementById('roomCode').value)}catch(x){setMsg(x.message)}})
 document.getElementById('saveProfile')?.addEventListener('click',async()=>{try{await CheckoutOnline.updateProfile({username:document.getElementById('username').value,display_name:document.getElementById('displayName').value});setMsg('✓ OK')}catch(x){setMsg(x.message)}})
 const scoreInputs=[...document.querySelectorAll('[data-online-score]')];
 const setScore=value=>scoreInputs.forEach(input=>{input.value=value});
 const cleanScore=value=>{const clean=String(value||'').replace(/\D/g,'').slice(0,3);return clean&&Number(clean)>180?'180':clean};
 scoreInputs.forEach(input=>{input.addEventListener('input',()=>setScore(cleanScore(input.value)));input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();input.closest('.online-entry')?.querySelector('[data-submit-visit]')?.click()}})});
 document.querySelectorAll('[data-key]').forEach(button=>button.addEventListener('click',()=>{const current=scoreInputs[0]?.value||'';const key=button.dataset.key;if(key==='back')setScore(current.slice(0,-1));else if(key==='ok')submitOnlineVisit(button.closest('.online-mobile-game'),button);else setScore(cleanScore(current+key))}));
 document.querySelectorAll('[data-submit-visit]').forEach(button=>button.addEventListener('click',()=>submitOnlineVisit(button.closest('.online-entry'),button)));
 document.querySelectorAll('[data-confirm-double]').forEach(button=>button.addEventListener('click',()=>sendOnlineVisit(pendingCheckout.score,+button.dataset.confirmDouble,button)));
 document.querySelector('[data-checkout-bust]')?.addEventListener('click',e=>sendOnlineVisit(pendingCheckout.score,null,e.currentTarget));
 document.querySelector('[data-checkout-cancel]')?.addEventListener('click',()=>{pendingCheckout=null;render()});
 if(snapshot?.match&&!window.matchMedia('(max-width:768px)').matches){
  const desktopScore=document.querySelector('.online-desktop-game [data-online-score]');desktopScore?.focus({preventScroll:true});
  document.onkeydown=e=>{if(e.ctrlKey||e.metaKey||e.altKey||document.querySelector('[role="dialog"]'))return;if(/^\d$/.test(e.key)&&document.activeElement!==desktopScore){e.preventDefault();setScore(cleanScore((desktopScore?.value||'')+e.key));desktopScore?.focus({preventScroll:true})}else if(e.key==='Enter'&&desktopScore?.value){e.preventDefault();document.querySelector('.online-desktop-game [data-submit-visit]')?.click()}}
 }else document.onkeydown=null;
 document.getElementById('copyCode')?.addEventListener('click',()=>navigator.clipboard.writeText(snapshot.match.room_code))
 document.getElementById('shareLink')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(CheckoutOnline.inviteUrl());setMsg('✓ '+T.copied)})
 document.getElementById('lobby')?.addEventListener('click',()=>CheckoutOnline.leaveMatch().catch(x=>setMsg(x.message)))
}
async function submitOnlineVisit(scope,button){
 try{const input=scope?.querySelector('[data-online-score]')||document.querySelector('[data-online-score]');const score=+input?.value;if(!Number.isInteger(score)||score<0||score>180)throw new Error('0–180');const player=snapshot.players.find(p=>p.user_id===snapshot.user.id);if(snapshot.match.double_out&&score===player?.remaining){pendingCheckout={score,doubles:validFinishDoubles(score)};render();return}await sendOnlineVisit(score,null,button)}catch(x){setMsg(x.message)}
}
async function sendOnlineVisit(score,checkoutDouble,button){
 const before=snapshot?.players?.find(p=>p.user_id===snapshot.user?.id)?.remaining;try{button.disabled=true;await CheckoutOnline.submitVisit(score,{dartsUsed:3,checkoutDouble});pendingCheckout=null;if(score===180&&(before>180||!snapshot.match.double_out&&before===180))showOnlineMoment()}catch(x){setMsg(x.message)}finally{button.disabled=false}
}
function showOnlineMoment(){const moment=document.createElement('div');moment.className='online-moment';moment.textContent='180!';document.body.append(moment);document.querySelectorAll('.online-score-ring,.online-mobile-hero').forEach(el=>el.animate?.([{transform:'scale(1)'},{transform:'scale(1.04)',filter:'brightness(1.7)'},{transform:'scale(1)'}],{duration:760,easing:'cubic-bezier(.2,.8,.2,1)'}));window.CheckoutAudio?.play?.('180');navigator.vibrate?.([80,40,120]);setTimeout(()=>moment.remove(),1100)}
document.getElementById('langBtn').addEventListener('click',()=>{location.href=isEn?'../online.html':'./en/online.html'});
CheckoutOnline.subscribe(s=>{snapshot=s;render()});CheckoutOnline.init().catch(e=>{snapshot={...CheckoutOnline.state};setMsg(e.message)});
})();
