(() => {
'use strict';
const root=document.getElementById('onlineApp');const isEn=location.pathname.startsWith('/en/');
const T={
 ru:{loading:'Загрузка…',notConfigured:'Online почти готов',needCfg:'Подключи Project URL и Publishable key Supabase — после этого этот экран заработает без изменения логики.',login:'Войти',signup:'Регистрация',email:'E-mail',pass:'Пароль',name:'Имя',profile:'Профиль',logout:'Выйти',create:'Создать онлайн-матч',join:'Войти по коду',room:'Комната',game:'Игра',legs:'Легов для победы',double:'Double Out',waiting:'Ждём второго игрока',copy:'Скопировать код',share:'Скопировать ссылку другу',copied:'Ссылка скопирована',score:'Сумма подхода',darts:'Дротиков',checkout:'Последнее удвоение',notCheckout:'Не закрытие',send:'ЗАПИСАТЬ ПОДХОД',turn:'ХОД',yourTurn:'ВАШ ХОД',opponentTurn:'ХОД СОПЕРНИКА',finished:'МАТЧ ЗАВЕРШЁН',history:'Последние подходы',back:'В лобби',error:'Ошибка',online:'Онлайн',connecting:'Подключение',fallback:'Резервная синхронизация',username:'Ник',save:'Сохранить профиль'},
 en:{loading:'Loading…',notConfigured:'Online is almost ready',needCfg:'Connect the Supabase Project URL and Publishable key — then this screen works without changing the game logic.',login:'Sign in',signup:'Create account',email:'Email',pass:'Password',name:'Name',profile:'Profile',logout:'Sign out',create:'Create online match',join:'Join by code',room:'Room',game:'Game',legs:'Legs to win',double:'Double Out',waiting:'Waiting for player two',copy:'Copy code',share:'Copy invite link',copied:'Invite link copied',score:'Visit score',darts:'Darts',checkout:'Finishing double',notCheckout:'Not a checkout',send:'SUBMIT VISIT',turn:'TURN',yourTurn:'YOUR TURN',opponentTurn:"OPPONENT'S TURN",finished:'MATCH FINISHED',history:'Recent visits',back:'Lobby',error:'Error',online:'Online',connecting:'Connecting',fallback:'Fallback sync',username:'Username',save:'Save profile'}
}[isEn?'en':'ru'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let snapshot=null,msg='';
const syncLabel=status=>status==='SUBSCRIBED'?T.online:status==='CONNECTING'?T.connecting:T.fallback;
function setMsg(s){msg=s;render()}
function authView(){
 return '<section class="ol-card"><h1>Checkout Lab <span style="color:var(--green)">Online</span></h1><p class="muted">'+(isEn?'Play 301/501 live from different locations.':'Играйте 301/501 в реальном времени из разных мест.')+'</p><div class="grid"><form id="loginForm" class="stack"><h2>'+T.login+'</h2><input name="email" type="email" placeholder="'+T.email+'" required><input name="password" type="password" placeholder="'+T.pass+'" minlength="6" required><button class="primary">'+T.login+'</button></form><form id="signupForm" class="stack"><h2>'+T.signup+'</h2><input name="displayName" placeholder="'+T.name+'" required><input name="email" type="email" placeholder="'+T.email+'" required><input name="password" type="password" placeholder="'+T.pass+'" minlength="6" required><button class="primary">'+T.signup+'</button></form></div>'+status()+'</section>'
}
function status(){return msg?'<p class="status '+(msg.startsWith('✓')?'ok':'err')+'">'+esc(msg)+'</p>':''}
function lobby(){
 const p=snapshot.profile||{};return '<div class="topbar"><div><span class="pill">'+T.online+'</span><h1>'+esc(p.display_name||p.username)+'</h1><p class="muted">@'+esc(p.username)+'</p></div><button id="logout" class="secondary">'+T.logout+'</button></div><div class="grid"><section class="ol-card stack"><h2>'+T.create+'</h2><label>'+T.game+'<select id="gameType"><option>501</option><option>301</option></select></label><label>'+T.legs+'<select id="legs"><option>1</option><option>2</option><option>3</option><option>5</option><option>7</option></select></label><label class="row"><input id="doubleOut" type="checkbox" checked style="width:auto"> '+T.double+'</label><button id="createMatch" class="primary">'+T.create+'</button></section><section class="ol-card stack"><h2>'+T.join+'</h2><input id="roomCode" maxlength="6" placeholder="ABC123" style="text-transform:uppercase;font-size:28px;font-weight:1000;letter-spacing:.12em"><button id="joinMatch" class="primary">'+T.join+'</button><hr style="width:100%;border:0;border-top:1px solid var(--line)"><h3>'+T.profile+'</h3><input id="username" value="'+esc(p.username||'')+'" placeholder="'+T.username+'"><input id="displayName" value="'+esc(p.display_name||'')+'" placeholder="'+T.name+'"><button id="saveProfile" class="secondary">'+T.save+'</button></section></div>'+status()
}
function matchView(){
 const m=snapshot.match,ps=snapshot.players||[];const waiting=ps.length<2;const pboxes=[0,1].map(i=>{const p=ps[i];if(!p)return '<div class="playerbox"><div class="name">…</div><div class="remaining">'+m.game_type+'</div><div class="legs">'+T.waiting+'</div></div>';const active=m.current_player_id===p.user_id;return '<div class="playerbox '+(active?'turn':'')+'"><div class="name">'+esc(p.profiles?.display_name||p.profiles?.username||'Player')+(active?'<span class="turn-tag">'+T.turn+'</span>':'')+'</div><div class="remaining">'+p.remaining+'</div><div class="legs">LEGS '+p.legs_won+' / '+m.legs_to_win+'</div></div>'}).join('<div class="vs">VS</div>');
 const mine=m.current_player_id===snapshot.user?.id&&m.status==='live';
 const hist=(snapshot.visits||[]).map(v=>'<div class="visit"><span>'+esc((ps.find(p=>p.user_id===v.user_id)?.profiles?.display_name)||'Player')+'</span><b>'+v.score+(v.bust?' BUST':'')+'</b><span>'+v.remaining_before+' → '+v.remaining_after+'</span></div>').join('');
 const doubles='<option value="">'+T.notCheckout+'</option>'+Array.from({length:20},(_,i)=>'<option value="'+(i+1)+'">D'+(i+1)+'</option>').join('')+'<option value="25">BULL</option>';
 const turnBanner=!waiting&&m.status==='live'?'<div class="turn-banner '+(mine?'':'wait')+'">'+(mine?'● '+T.yourTurn:T.opponentTurn)+'</div>':'';
 return '<div class="topbar"><div class="match-meta"><div><div class="room-label">'+T.room+'</div><div class="room-code">'+m.room_code+'</div></div><span class="pill">'+m.game_type+' · '+(m.double_out?'DOUBLE OUT':'STRAIGHT OUT')+' · '+esc(syncLabel(snapshot.realtimeStatus))+'</span></div><button id="lobby" class="secondary">'+T.back+'</button></div><section class="ol-card match-card"><div class="scoreboard">'+pboxes+'</div>'+turnBanner+(waiting?'<div class="row" style="justify-content:center;margin-top:18px"><button id="copyCode" class="secondary">'+T.copy+'</button><button id="shareLink" class="primary">'+T.share+'</button></div>':'')+(mine?'<div class="visitbox stack"><span class="score-label">'+T.score+'</span><div class="visitline"><label class="score-field"><input id="visitScore" type="number" min="0" max="180" inputmode="numeric" autocomplete="off" aria-label="'+T.score+'" placeholder="0–180"></label><label>'+T.darts+'<select id="dartsUsed"><option value="3">3 '+T.darts+'</option><option value="2">2 '+T.darts+'</option><option value="1">1 '+T.darts+'</option></select></label>'+(m.double_out?'<label>'+T.checkout+'<select id="checkoutDouble">'+doubles+'</select></label>':'')+'</div><button id="submitVisit" class="primary submit-visit">'+T.send+'</button></div>':'')+(m.status==='finished'?'<h2 style="text-align:center;color:var(--green);margin-top:20px">'+T.finished+'</h2>':'')+'<div class="history"><h3>'+T.history+'</h3><div class="history-list">'+hist+'</div></div></section>'+status()
}
function render(){
 if(!snapshot){root.innerHTML='<section class="ol-card"><h1>'+T.loading+'</h1></section>';return}
 if(!snapshot.client){root.innerHTML='<section class="ol-card"><h1>'+T.notConfigured+'</h1><p class="muted">'+T.needCfg+'</p></section>';return}
 root.innerHTML=!snapshot.user?authView():snapshot.match?matchView():lobby();bind()
}
function bind(){
 document.getElementById('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await CheckoutOnline.signIn(f.get('email'),f.get('password'));setMsg('✓ OK')}catch(x){setMsg(x.message)}})
 document.getElementById('signupForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await CheckoutOnline.signUp(f.get('email'),f.get('password'),f.get('displayName'));setMsg('✓ '+(isEn?'Check your email if confirmation is enabled.':'Если включено подтверждение, проверьте почту.'))}catch(x){setMsg(x.message)}})
 document.getElementById('logout')?.addEventListener('click',()=>CheckoutOnline.signOut().catch(x=>setMsg(x.message)))
 document.getElementById('createMatch')?.addEventListener('click',async()=>{try{await CheckoutOnline.createMatch({gameType:+document.getElementById('gameType').value,legsToWin:+document.getElementById('legs').value,doubleOut:document.getElementById('doubleOut').checked})}catch(x){setMsg(x.message)}})
 document.getElementById('joinMatch')?.addEventListener('click',async()=>{try{await CheckoutOnline.joinMatch(document.getElementById('roomCode').value)}catch(x){setMsg(x.message)}})
 document.getElementById('saveProfile')?.addEventListener('click',async()=>{try{await CheckoutOnline.updateProfile({username:document.getElementById('username').value,display_name:document.getElementById('displayName').value});setMsg('✓ OK')}catch(x){setMsg(x.message)}})
 document.getElementById('submitVisit')?.addEventListener('click',async e=>{const button=e.currentTarget;try{button.disabled=true;const score=+document.getElementById('visitScore').value;if(!Number.isInteger(score)||score<0||score>180)throw new Error('0–180');const raw=document.getElementById('checkoutDouble')?.value;await CheckoutOnline.submitVisit(score,{dartsUsed:+document.getElementById('dartsUsed').value,checkoutDouble:raw?+raw:null})}catch(x){setMsg(x.message)}finally{button.disabled=false}})
 document.getElementById('copyCode')?.addEventListener('click',()=>navigator.clipboard.writeText(snapshot.match.room_code))
 document.getElementById('shareLink')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(CheckoutOnline.inviteUrl());setMsg('✓ '+T.copied)})
 document.getElementById('lobby')?.addEventListener('click',()=>CheckoutOnline.leaveMatch().catch(x=>setMsg(x.message)))
}
document.getElementById('langBtn').addEventListener('click',()=>{location.href=isEn?'../online.html':'./en/online.html'});
CheckoutOnline.subscribe(s=>{snapshot=s;render()});CheckoutOnline.init().catch(e=>{snapshot={...CheckoutOnline.state};setMsg(e.message)});
})();
